<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/RawGLTF/bot/ybot.glb
-->

<script>
  import { Group, MeshStandardMaterial } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations, FakeGlowMaterial} from '@threlte/extras'
  import { base } from '$app/paths';

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const gltf = useGltf(base + '/RawGLTF/bot/ybot.glb')

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group
        name="Armature"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="Alpha_Joints"
          geometry={gltf.nodes.Alpha_Joints.geometry}
          material={gltf.materials.Alpha_Joints_MAT}
          skeleton={gltf.nodes.Alpha_Joints.skeleton}
          castShadow
        >
          <T.MeshStandardMaterial color="white" emissive="white" emissiveIntensity={2}/>
        </T.SkinnedMesh>


        <T.SkinnedMesh
          name="Alpha_Surface"
          geometry={gltf.nodes.Alpha_Surface.geometry}
          material={gltf.materials.Alpha_Body_MAT}
          skeleton={gltf.nodes.Alpha_Surface.skeleton}
          castShadow
        >
        <T.MeshStandardMaterial color="#d4af37" roughness={0.3} metalness={0.8}/>
        </T.SkinnedMesh>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
